pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code...'
                checkout scm
            }
        }
        
        stage('Install Dependencies') {
            steps {
                echo 'Installing dependencies...'
                sh 'pip install -r requirements.txt'
            }
        }
        
        stage('Run Tests') {
            steps {
                echo 'Running tests...'
                sh 'pytest tests/'
            }
        }
        
        stage('Build') {
            steps {
                echo 'Building application...'
                sh 'python -m py_compile app/main.py'
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline completed!'
        }
    }
}
